package cn.edu.zuel.common.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("advert", "id", Advert.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("chat", "id", Chat.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("complain", "id", Complain.class);
		arp.addMapping("contract", "id", Contract.class);
		arp.addMapping("favorites", "id", Favorites.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("firm", "id", Firm.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("industry", "id", Industry.class);
		arp.addMapping("login_info", "id", LoginInfo.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("order_info", "id", OrderInfo.class);
		arp.addMapping("recharge", "id", Recharge.class);
		arp.addMapping("stock", "id", Stock.class);
		arp.addMapping("trade", "id", Trade.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_address", "id", UserAddress.class);
		arp.addMapping("user_session", "id", UserSession.class);
	}
}

