package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseAdvert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advert extends BaseAdvert<Advert> {
	public static final Advert dao = new Advert().dao();
}
