package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
}
