package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand().dao();
}
