package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category().dao();
}
