package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseChat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chat extends BaseChat<Chat> {
	public static final Chat dao = new Chat().dao();
}
