package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment().dao();
}
