package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseComplain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Complain extends BaseComplain<Complain> {
	public static final Complain dao = new Complain().dao();
}
