package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contract extends BaseContract<Contract> {
	public static final Contract dao = new Contract().dao();
}
