package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorites extends BaseFavorites<Favorites> {
	public static final Favorites dao = new Favorites().dao();
}
