package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File().dao();
}
