package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseFirm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Firm extends BaseFirm<Firm> {
	public static final Firm dao = new Firm().dao();
}
