package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseIndustry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Industry extends BaseIndustry<Industry> {
	public static final Industry dao = new Industry().dao();
}
