package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	public static final OrderInfo dao = new OrderInfo().dao();
}
