package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recharge extends BaseRecharge<Recharge> {
	public static final Recharge dao = new Recharge().dao();
}
