package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stock extends BaseStock<Stock> {
	public static final Stock dao = new Stock().dao();
}
