package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trade extends BaseTrade<Trade> {
	public static final Trade dao = new Trade().dao();
}
