package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
}
