package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAddress extends BaseUserAddress<UserAddress> {
	public static final UserAddress dao = new UserAddress().dao();
}
