package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 文件名 文件上传时姓名
	 */
	public void setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
	}
	
	/**
	 * 文件名 文件上传时姓名
	 */
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}
	
	/**
	 * 文件来源 1-IM，2-其他
	 */
	public void setSource(java.lang.Integer source) {
		set("source", source);
	}
	
	/**
	 * 文件来源 1-IM，2-其他
	 */
	public java.lang.Integer getSource() {
		return getInt("source");
	}
	
	/**
	 * 文件类型 1-文本文件 2-图片文件 3-音频文件 4-视频文件 5-其他文件
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 文件类型 1-文本文件 2-图片文件 3-音频文件 4-视频文件 5-其他文件
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 文件后缀名 后缀名为jpg/png等，无.
	 */
	public void setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
	}
	
	/**
	 * 文件后缀名 后缀名为jpg/png等，无.
	 */
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}
	
	/**
	 * 文件存储地址 文件在服务器上存储路径
	 */
	public void setSavedPath(java.lang.String savedPath) {
		set("saved_path", savedPath);
	}
	
	/**
	 * 文件存储地址 文件在服务器上存储路径
	 */
	public java.lang.String getSavedPath() {
		return getStr("saved_path");
	}
	
	/**
	 * 文件远程存储路径 如果文件从远程获取，则存在
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 文件远程存储路径 如果文件从远程获取，则存在
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 文件新名称 文件新名称
	 */
	public void setNewName(java.lang.String newName) {
		set("new_name", newName);
	}
	
	/**
	 * 文件新名称 文件新名称
	 */
	public java.lang.String getNewName() {
		return getStr("new_name");
	}
	
	/**
	 * 文件内容 需要存储文件内容时，则将生成的文件存储到文本内容表中，通过uuid关联
	 */
	public void setTextContentUuid(java.lang.String textContentUuid) {
		set("text_content_uuid", textContentUuid);
	}
	
	/**
	 * 文件内容 需要存储文件内容时，则将生成的文件存储到文本内容表中，通过uuid关联
	 */
	public java.lang.String getTextContentUuid() {
		return getStr("text_content_uuid");
	}
	
	/**
	 * 文件下载次数
	 */
	public void setDownloadTimes(java.lang.Integer downloadTimes) {
		set("download_times", downloadTimes);
	}
	
	/**
	 * 文件下载次数
	 */
	public java.lang.Integer getDownloadTimes() {
		return getInt("download_times");
	}
	
	/**
	 * 文件所属对象
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	/**
	 * 文件所属对象
	 */
	public java.lang.String getUuid() {
		return getStr("uuid");
	}
	
	/**
	 * 文件mimeType
	 */
	public void setMimeType(java.lang.String mimeType) {
		set("mime_type", mimeType);
	}
	
	/**
	 * 文件mimeType
	 */
	public java.lang.String getMimeType() {
		return getStr("mime_type");
	}
	
	/**
	 * 文件大小
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}
	
	/**
	 * 额外参数 额外参数，如果是语音文件，则对应时长，图片文件则包括宽和高
	 */
	public void setExtraParams(java.lang.String extraParams) {
		set("extra_params", extraParams);
	}
	
	/**
	 * 额外参数 额外参数，如果是语音文件，则对应时长，图片文件则包括宽和高
	 */
	public java.lang.String getExtraParams() {
		return getStr("extra_params");
	}
	
	/**
	 * 上传用户
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 上传用户
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 是否删除 0-未删除，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
