package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComplain<M extends BaseComplain<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 用户编号
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 投诉对象 0-对厂商,1-对平台
	 */
	public void setTarget(java.lang.Integer target) {
		set("target", target);
	}
	
	/**
	 * 投诉对象 0-对厂商,1-对平台
	 */
	public java.lang.Integer getTarget() {
		return getInt("target");
	}
	
	/**
	 * 反馈类型 0-发货问题,1-承诺未履行,2-产品服务问题,3-其他；4-
	 */
	public void setFeedbackType(java.lang.Integer feedbackType) {
		set("feedback_type", feedbackType);
	}
	
	/**
	 * 反馈类型 0-发货问题,1-承诺未履行,2-产品服务问题,3-其他；4-
	 */
	public java.lang.Integer getFeedbackType() {
		return getInt("feedback_type");
	}
	
	/**
	 * 投诉内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 投诉内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 投诉图片 文件路径？？
	 */
	public void setPictureId(java.math.BigInteger pictureId) {
		set("picture_id", pictureId);
	}
	
	/**
	 * 投诉图片 文件路径？？
	 */
	public java.math.BigInteger getPictureId() {
		return get("picture_id");
	}
	
	/**
	 * 投诉图片名
	 */
	public void setPictureName(java.lang.String pictureName) {
		set("picture_name", pictureName);
	}
	
	/**
	 * 投诉图片名
	 */
	public java.lang.String getPictureName() {
		return getStr("picture_name");
	}
	
	/**
	 * 状态 0-未处理，1-已处理
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0-未处理，1-已处理
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
