package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderInfo<M extends BaseOrderInfo<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 用户编号
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 商品编号
	 */
	public void setGoodsId(java.math.BigInteger goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品编号
	 */
	public java.math.BigInteger getGoodsId() {
		return get("goods_id");
	}
	
	/**
	 * 库存编号
	 */
	public void setStockId(java.math.BigInteger stockId) {
		set("stock_id", stockId);
	}
	
	/**
	 * 库存编号
	 */
	public java.math.BigInteger getStockId() {
		return get("stock_id");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 共享租赁用户编号
	 */
	public void setOtherUserId(java.math.BigInteger otherUserId) {
		set("other_user_id", otherUserId);
	}
	
	/**
	 * 共享租赁用户编号
	 */
	public java.math.BigInteger getOtherUserId() {
		return get("other_user_id");
	}
	
	/**
	 * 订单类型 0-以租代售，1-共享租赁，3-先租后售,4-学生租赁
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 订单类型 0-以租代售，1-共享租赁，3-先租后售,4-学生租赁
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 租赁时间 天数
	 */
	public void setRentTime(java.lang.Integer rentTime) {
		set("rent_time", rentTime);
	}
	
	/**
	 * 租赁时间 天数
	 */
	public java.lang.Integer getRentTime() {
		return getInt("rent_time");
	}
	
	/**
	 * 续租时间
	 */
	public void setReletTime(java.lang.Integer reletTime) {
		set("relet_time", reletTime);
	}
	
	/**
	 * 续租时间
	 */
	public java.lang.Integer getReletTime() {
		return getInt("relet_time");
	}
	
	/**
	 * 租赁开始时间
	 */
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	/**
	 * 租赁开始时间
	 */
	public java.util.Date getStartTime() {
		return get("start_time");
	}
	
	/**
	 * 订单状态 0-所有订单，1-提交订单，2-未支付，3-已支付未发货，4-已支付已发货，5-已签收，6-是否续租，7-是否购买，
8-退租，9-租赁结束正在返还，10-租赁结束商家退款，11-已取消
	 */
	public void setOrderState(java.lang.Integer orderState) {
		set("order_state", orderState);
	}
	
	/**
	 * 订单状态 0-所有订单，1-提交订单，2-未支付，3-已支付未发货，4-已支付已发货，5-已签收，6-是否续租，7-是否购买，
8-退租，9-租赁结束正在返还，10-租赁结束商家退款，11-已取消
	 */
	public java.lang.Integer getOrderState() {
		return getInt("order_state");
	}
	
	/**
	 * 租赁结束时间
	 */
	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	/**
	 * 租赁结束时间
	 */
	public java.util.Date getEndTime() {
		return get("end_time");
	}
	
	/**
	 * 支付状态 0-未支付，1-已支付
	 */
	public void setPayState(java.lang.Integer payState) {
		set("pay_state", payState);
	}
	
	/**
	 * 支付状态 0-未支付，1-已支付
	 */
	public java.lang.Integer getPayState() {
		return getInt("pay_state");
	}
	
	/**
	 * 押金
	 */
	public void setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
	}
	
	/**
	 * 押金
	 */
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}
	
	/**
	 * 租金
	 */
	public void setRental(java.math.BigDecimal rental) {
		set("rental", rental);
	}
	
	/**
	 * 租金
	 */
	public java.math.BigDecimal getRental() {
		return get("rental");
	}
	
	/**
	 * 返还地址 厂商地址
	 */
	public void setFirmAddr(java.math.BigInteger firmAddr) {
		set("firm_addr", firmAddr);
	}
	
	/**
	 * 返还地址 厂商地址
	 */
	public java.math.BigInteger getFirmAddr() {
		return get("firm_addr");
	}
	
	/**
	 * 用户地址 用户地址
	 */
	public void setUserAddr(java.math.BigInteger userAddr) {
		set("user_addr", userAddr);
	}
	
	/**
	 * 用户地址 用户地址
	 */
	public java.math.BigInteger getUserAddr() {
		return get("user_addr");
	}
	
	public void setSharingAddr(java.lang.Long sharingAddr) {
		set("sharing_addr", sharingAddr);
	}
	
	public java.lang.Long getSharingAddr() {
		return getLong("sharing_addr");
	}
	
	/**
	 * 交易号
	 */
	public void setTradeId(java.math.BigInteger tradeId) {
		set("trade_id", tradeId);
	}
	
	/**
	 * 交易号
	 */
	public java.math.BigInteger getTradeId() {
		return get("trade_id");
	}
	
	/**
	 * 合同号
	 */
	public void setContractId(java.math.BigInteger contractId) {
		set("contract_id", contractId);
	}
	
	/**
	 * 合同号
	 */
	public java.math.BigInteger getContractId() {
		return get("contract_id");
	}
	
	/**
	 * 物流单号
	 */
	public void setLogisticsId(java.math.BigInteger logisticsId) {
		set("logistics_id", logisticsId);
	}
	
	/**
	 * 物流单号
	 */
	public java.math.BigInteger getLogisticsId() {
		return get("logistics_id");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
