package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFirm<M extends BaseFirm<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 法人姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 法人姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setBankCard(java.lang.String bankCard) {
		set("bankCard", bankCard);
	}
	
	public java.lang.String getBankCard() {
		return getStr("bankCard");
	}
	
	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}
	
	public java.math.BigDecimal getBalance() {
		return get("balance");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}
	
	/**
	 * 法人身份证复印件ID
	 */
	public void setIdCardPicId(java.math.BigInteger idCardPicId) {
		set("id_card_pic_id", idCardPicId);
	}
	
	/**
	 * 法人身份证复印件ID
	 */
	public java.math.BigInteger getIdCardPicId() {
		return get("id_card_pic_id");
	}
	
	/**
	 * 法人身份证复印件名称
	 */
	public void setIdCardPicName(java.lang.String idCardPicName) {
		set("id_card_pic_name", idCardPicName);
	}
	
	/**
	 * 法人身份证复印件名称
	 */
	public java.lang.String getIdCardPicName() {
		return getStr("id_card_pic_name");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 厂商名称
	 */
	public void setFirmName(java.lang.String firmName) {
		set("firm_name", firmName);
	}
	
	/**
	 * 厂商名称
	 */
	public java.lang.String getFirmName() {
		return getStr("firm_name");
	}
	
	/**
	 * 所属行业
	 */
	public void setIndustryId(java.math.BigInteger industryId) {
		set("industry_id", industryId);
	}
	
	/**
	 * 所属行业
	 */
	public java.math.BigInteger getIndustryId() {
		return get("industry_id");
	}
	
	/**
	 * 厂商主营相关信息 主营业务
	 */
	public void setInfo(java.lang.String info) {
		set("info", info);
	}
	
	/**
	 * 厂商主营相关信息 主营业务
	 */
	public java.lang.String getInfo() {
		return getStr("info");
	}
	
	/**
	 * 企业注册号
	 */
	public void setRegistration(java.lang.String registration) {
		set("registration", registration);
	}
	
	/**
	 * 企业注册号
	 */
	public java.lang.String getRegistration() {
		return getStr("registration");
	}
	
	/**
	 * 营业执照
	 */
	public void setLicenseId(java.math.BigInteger licenseId) {
		set("license_id", licenseId);
	}
	
	/**
	 * 营业执照
	 */
	public java.math.BigInteger getLicenseId() {
		return get("license_id");
	}
	
	/**
	 * 营业执照名称
	 */
	public void setLicenseName(java.lang.String licenseName) {
		set("license_name", licenseName);
	}
	
	/**
	 * 营业执照名称
	 */
	public java.lang.String getLicenseName() {
		return getStr("license_name");
	}
	
	/**
	 * 默认地址
	 */
	public void setAddressId(java.math.BigInteger addressId) {
		set("address_id", addressId);
	}
	
	/**
	 * 默认地址
	 */
	public java.math.BigInteger getAddressId() {
		return get("address_id");
	}
	
	/**
	 * 加密盐
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 审核状态 0-未审核， 1-正常 2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 审核状态 0-未审核， 1-正常 2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 信用等级
	 */
	public void setCredit(java.lang.Integer credit) {
		set("credit", credit);
	}
	
	/**
	 * 信用等级
	 */
	public java.lang.Integer getCredit() {
		return getInt("credit");
	}
	
	/**
	 * 信用分 刚注册的淘宝账号信用为零。要想得到信用，可以通过购物实现
	 */
	public void setCreditScore(java.lang.Integer creditScore) {
		set("credit_score", creditScore);
	}
	
	/**
	 * 信用分 刚注册的淘宝账号信用为零。要想得到信用，可以通过购物实现
	 */
	public java.lang.Integer getCreditScore() {
		return getInt("credit_score");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
