package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBrand<M extends BaseBrand<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 品牌名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 品牌名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 分类
	 */
	public void setCategoryId(java.math.BigInteger categoryId) {
		set("category_id", categoryId);
	}
	
	/**
	 * 分类
	 */
	public java.math.BigInteger getCategoryId() {
		return get("category_id");
	}
	
	/**
	 * 品牌logoID
	 */
	public void setLogoId(java.lang.String logoId) {
		set("logo_id", logoId);
	}
	
	/**
	 * 品牌logoID
	 */
	public java.lang.String getLogoId() {
		return getStr("logo_id");
	}
	
	/**
	 * 品牌logo
	 */
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}
	
	/**
	 * 品牌logo
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}
	
	/**
	 * 品牌描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 品牌描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 状态 0-未审核，1-已审核，2-审核为通过
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0-未审核，1-已审核，2-审核为通过
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
