package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChat<M extends BaseChat<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 发起者 0-用户，1-厂商
	 */
	public void setInitiator(java.lang.Integer initiator) {
		set("initiator", initiator);
	}
	
	/**
	 * 发起者 0-用户，1-厂商
	 */
	public java.lang.Integer getInitiator() {
		return getInt("initiator");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 用户编号
	 */
	public void setClientId(java.math.BigInteger clientId) {
		set("client_id", clientId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getClientId() {
		return get("client_id");
	}
	
	/**
	 * 消息详情
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}
	
	/**
	 * 消息详情
	 */
	public java.lang.String getRecord() {
		return getStr("record");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
