package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 发送至 0-用户，1-厂商
	 */
	public void setReceiver(java.lang.Integer receiver) {
		set("receiver", receiver);
	}
	
	/**
	 * 发送至 0-用户，1-厂商
	 */
	public java.lang.Integer getReceiver() {
		return getInt("receiver");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 用户编号
	 */
	public void setClientId(java.math.BigInteger clientId) {
		set("client_id", clientId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getClientId() {
		return get("client_id");
	}
	
	/**
	 * 消息详情
	 */
	public void setMessage(java.lang.String message) {
		set("message", message);
	}
	
	/**
	 * 消息详情
	 */
	public java.lang.String getMessage() {
		return getStr("message");
	}
	
	/**
	 * 是否已读 0-未读，1-已读
	 */
	public void setIsRead(java.lang.Integer isRead) {
		set("is_read", isRead);
	}
	
	/**
	 * 是否已读 0-未读，1-已读
	 */
	public java.lang.Integer getIsRead() {
		return getInt("is_read");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
