package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdvert<M extends BaseAdvert<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 图片
	 */
	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getImage() {
		return getStr("image");
	}
	
	/**
	 * 链接地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 链接地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 状态 0-所有，1-启用，2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0-所有，1-启用，2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 图片ID
	 */
	public void setImageId(java.lang.String imageId) {
		set("image_id", imageId);
	}
	
	/**
	 * 图片ID
	 */
	public java.lang.String getImageId() {
		return getStr("image_id");
	}
	
}
