package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrade<M extends BaseTrade<M>> extends Model<M> implements IBean {

	/**
	 * 交易号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 交易号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 订单编号
	 */
	public void setOrderId(java.math.BigInteger orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 订单编号
	 */
	public java.math.BigInteger getOrderId() {
		return get("order_id");
	}
	
	/**
	 * 用户编号
	 */
	public void setClientId(java.math.BigInteger clientId) {
		set("client_id", clientId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getClientId() {
		return get("client_id");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 支付方式 0-查询所有，1-银行卡,2-支付宝
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 支付方式 0-查询所有，1-银行卡,2-支付宝
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 支付金额
	 */
	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}
	
	/**
	 * 支付金额
	 */
	public java.math.BigDecimal getMoney() {
		return get("money");
	}
	
	/**
	 * 押金所处位置 0-平台，1-客户，2-厂商
	 */
	public void setDepositPosition(java.lang.Integer depositPosition) {
		set("deposit_position", depositPosition);
	}
	
	/**
	 * 押金所处位置 0-平台，1-客户，2-厂商
	 */
	public java.lang.Integer getDepositPosition() {
		return getInt("deposit_position");
	}
	
	/**
	 * 租金所处位置 0-平台，1-客户，2-厂商
	 */
	public void setRentalPosition(java.lang.Integer rentalPosition) {
		set("rental_position", rentalPosition);
	}
	
	/**
	 * 租金所处位置 0-平台，1-客户，2-厂商
	 */
	public java.lang.Integer getRentalPosition() {
		return getInt("rental_position");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
