package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginInfo<M extends BaseLoginInfo<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 用户sessionId
	 */
	public void setSessionId(java.math.BigInteger sessionId) {
		set("session_id", sessionId);
	}
	
	/**
	 * 用户sessionId
	 */
	public java.math.BigInteger getSessionId() {
		return get("session_id");
	}
	
	/**
	 * 登录账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 登录IP地址
	 */
	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	/**
	 * 登录IP地址
	 */
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}
	
	/**
	 * 登录地址
	 */
	public void setLoginLocation(java.lang.String loginLocation) {
		set("login_location", loginLocation);
	}
	
	/**
	 * 登录地址
	 */
	public java.lang.String getLoginLocation() {
		return getStr("login_location");
	}
	
	/**
	 * 浏览器类型
	 */
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	/**
	 * 浏览器类型
	 */
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	/**
	 * 操作系统
	 */
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	/**
	 * 操作系统
	 */
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	/**
	 * 登录状态 1-登录成功 2-登录失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 登录状态 1-登录成功 2-登录失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 提示消息
	 */
	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	/**
	 * 提示消息
	 */
	public java.lang.String getMsg() {
		return getStr("msg");
	}
	
	/**
	 * 是否删除 0-未删除，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	public void setUntitled(java.lang.String untitled) {
		set("untitled", untitled);
	}
	
	public java.lang.String getUntitled() {
		return getStr("untitled");
	}
	
}
