package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserSession<M extends BaseUserSession<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 对应用户
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 对应用户
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 统一认证信息
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}
	
	/**
	 * 统一认证信息
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}
	
	/**
	 * 有效时间
	 */
	public void setExpiresIn(java.math.BigInteger expiresIn) {
		set("expires_in", expiresIn);
	}
	
	/**
	 * 有效时间
	 */
	public java.math.BigInteger getExpiresIn() {
		return get("expires_in");
	}
	
	/**
	 * 超时
	 */
	public void setExpiresTime(java.math.BigInteger expiresTime) {
		set("expires_time", expiresTime);
	}
	
	/**
	 * 超时
	 */
	public java.math.BigInteger getExpiresTime() {
		return get("expires_time");
	}
	
	/**
	 * 是否被强制退出 0-否 1-是
	 */
	public void setIsForceQuit(java.lang.Integer isForceQuit) {
		set("is_force_quit", isForceQuit);
	}
	
	/**
	 * 是否被强制退出 0-否 1-是
	 */
	public java.lang.Integer getIsForceQuit() {
		return getInt("is_force_quit");
	}
	
	/**
	 * 用户类型 0-用户，1-管理员，2-厂商
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 用户类型 0-用户，1-管理员，2-厂商
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
