package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 厂商编号
	 */
	public void setFirmId(java.math.BigInteger firmId) {
		set("firm_id", firmId);
	}
	
	/**
	 * 厂商编号
	 */
	public java.math.BigInteger getFirmId() {
		return get("firm_id");
	}
	
	/**
	 * 商品名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 是否为学生租赁 0-否，1-是
	 */
	public void setStuGoods(java.lang.Integer stuGoods) {
		set("stu_goods", stuGoods);
	}
	
	/**
	 * 是否为学生租赁 0-否，1-是
	 */
	public java.lang.Integer getStuGoods() {
		return getInt("stu_goods");
	}
	
	/**
	 * 品牌
	 */
	public void setBrandId(java.math.BigInteger brandId) {
		set("brand_id", brandId);
	}
	
	/**
	 * 品牌
	 */
	public java.math.BigInteger getBrandId() {
		return get("brand_id");
	}
	
	/**
	 * 商品分类
	 */
	public void setCategoryId(java.math.BigInteger categoryId) {
		set("category_id", categoryId);
	}
	
	/**
	 * 商品分类
	 */
	public java.math.BigInteger getCategoryId() {
		return get("category_id");
	}
	
	/**
	 * 商品详细描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 商品详细描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 商品概要
	 */
	public void setAbstract(java.lang.String _abstract) {
		set("abstract", _abstract);
	}
	
	/**
	 * 商品概要
	 */
	public java.lang.String getAbstract() {
		return getStr("abstract");
	}
	
	/**
	 * 是否可买 0-所有，1-可买，2-不可买
	 */
	public void setIsSale(java.lang.Integer isSale) {
		set("is_sale", isSale);
	}
	
	/**
	 * 是否可买 0-所有，1-可买，2-不可买
	 */
	public java.lang.Integer getIsSale() {
		return getInt("is_sale");
	}
	
	/**
	 * 上下架 0-上架，1-下架
	 */
	public void setGrounding(java.lang.Integer grounding) {
		set("grounding", grounding);
	}
	
	/**
	 * 上下架 0-上架，1-下架
	 */
	public java.lang.Integer getGrounding() {
		return getInt("grounding");
	}
	
	/**
	 * 押金
	 */
	public void setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
	}
	
	/**
	 * 押金
	 */
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}
	
	/**
	 * 租金
	 */
	public void setRental(java.math.BigDecimal rental) {
		set("rental", rental);
	}
	
	/**
	 * 租金
	 */
	public java.math.BigDecimal getRental() {
		return get("rental");
	}
	
	/**
	 * 最短租赁时长
	 */
	public void setRentTime(java.lang.Integer rentTime) {
		set("rent_time", rentTime);
	}
	
	/**
	 * 最短租赁时长
	 */
	public java.lang.Integer getRentTime() {
		return getInt("rent_time");
	}
	
	/**
	 * 购买价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 购买价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 图片ID
	 */
	public void setImageId(java.lang.String imageId) {
		set("image_id", imageId);
	}
	
	/**
	 * 图片ID
	 */
	public java.lang.String getImageId() {
		return getStr("image_id");
	}
	
	/**
	 * 图片名称
	 */
	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	/**
	 * 图片名称
	 */
	public java.lang.String getImage() {
		return getStr("image");
	}
	
	/**
	 * 库存
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	/**
	 * 库存
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}
	
	/**
	 * 已经租赁库存数
	 */
	public void setRentalNum(java.lang.Integer rentalNum) {
		set("rental_num", rentalNum);
	}
	
	/**
	 * 已经租赁库存数
	 */
	public java.lang.Integer getRentalNum() {
		return getInt("rental_num");
	}
	
	/**
	 * 已售库存数
	 */
	public void setSaleNum(java.lang.Integer saleNum) {
		set("sale_num", saleNum);
	}
	
	/**
	 * 已售库存数
	 */
	public java.lang.Integer getSaleNum() {
		return getInt("sale_num");
	}
	
	/**
	 * 审核状态 0-未审核，1-审核通过，2-审核不通过
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 审核状态 0-未审核，1-审核通过，2-审核不通过
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
