package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 商品编号
	 */
	public void setGoodsId(java.math.BigInteger goodsId) {
		set("goods_id", goodsId);
	}
	
	/**
	 * 商品编号
	 */
	public java.math.BigInteger getGoodsId() {
		return get("goods_id");
	}
	
	/**
	 * 用户编号
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户编号
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 商品评价
	 */
	public void setGoodsComment(java.lang.String goodsComment) {
		set("goods_comment", goodsComment);
	}
	
	/**
	 * 商品评价
	 */
	public java.lang.String getGoodsComment() {
		return getStr("goods_comment");
	}
	
	/**
	 * 评分 0,1,2,3,4个等级
	 */
	public void setMark(java.lang.Integer mark) {
		set("mark", mark);
	}
	
	/**
	 * 评分 0,1,2,3,4个等级
	 */
	public java.lang.Integer getMark() {
		return getInt("mark");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
