package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 编号
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 性别 0-所有，1-男，2-女
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别 0-所有，1-男，2-女
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}
	
	/**
	 * 是否学生 0-所有，1-是，2-否
	 */
	public void setIsStudent(java.lang.Integer isStudent) {
		set("is_student", isStudent);
	}
	
	/**
	 * 是否学生 0-所有，1-是，2-否
	 */
	public java.lang.Integer getIsStudent() {
		return getInt("is_student");
	}
	
	/**
	 * 账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}
	
	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 默认地址 对应地址表里面的编号
	 */
	public void setAddress(java.math.BigInteger address) {
		set("address", address);
	}
	
	/**
	 * 默认地址 对应地址表里面的编号
	 */
	public java.math.BigInteger getAddress() {
		return get("address");
	}
	
	/**
	 * 支付宝信息
	 */
	public void setAlipay(java.lang.String Alipay) {
		set("Alipay", Alipay);
	}
	
	/**
	 * 支付宝信息
	 */
	public java.lang.String getAlipay() {
		return getStr("Alipay");
	}
	
	/**
	 * 银行卡
	 */
	public void setBankCard(java.lang.String bankCard) {
		set("bankCard", bankCard);
	}
	
	/**
	 * 银行卡
	 */
	public java.lang.String getBankCard() {
		return getStr("bankCard");
	}
	
	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}
	
	public java.math.BigDecimal getBalance() {
		return get("balance");
	}
	
	/**
	 * 信用等级
	 */
	public void setCredit(java.lang.Integer credit) {
		set("credit", credit);
	}
	
	/**
	 * 信用等级
	 */
	public java.lang.Integer getCredit() {
		return getInt("credit");
	}
	
	/**
	 * 信用分 刚注册的淘宝账号信用为零。要想得到信用，可以通过购物实现
	 */
	public void setCreditScore(java.lang.Integer creditScore) {
		set("credit_score", creditScore);
	}
	
	/**
	 * 信用分 刚注册的淘宝账号信用为零。要想得到信用，可以通过购物实现
	 */
	public java.lang.Integer getCreditScore() {
		return getInt("credit_score");
	}
	
	/**
	 * 加密盐
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 状态 用户状态 1-正常 2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 用户状态 1-正常 2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 头像ID
	 */
	public void setPhotoFileId(java.math.BigInteger photoFileId) {
		set("photo_file_id", photoFileId);
	}
	
	/**
	 * 头像ID
	 */
	public java.math.BigInteger getPhotoFileId() {
		return get("photo_file_id");
	}
	
	/**
	 * 头像文件名称
	 */
	public void setPhotoFileName(java.lang.String photoFileName) {
		set("photo_file_name", photoFileName);
	}
	
	/**
	 * 头像文件名称
	 */
	public java.lang.String getPhotoFileName() {
		return getStr("photo_file_name");
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除,1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
}
